### ISSUE TITLE
Drizzle scaling and monsoon scaling parametrs don't work at all

### ISSUE THREAD

**Issue by MeatMorning** [prodzpod/Downpour#3]
Changing either (or both) scalings have no effect on difficulty descriptions and in-game difficulty as well. They always work as 600 and 300 seconds respectivly no matter what values you use.

![image](https://github.com/prodzpod/Downpour/assets/83251131/7fe38253-55ff-4255-9ca4-e218c96496a8)
![image](https://github.com/prodzpod/Downpour/assets/83251131/ca703534-1502-4861-ae21-9ed7ec6b3548)

**Comment by MeatMorning** [comment]
Curiously, downpour's values actually work as intended. Fresh profile test shows it isn't compatability issue as a problems remains even if downpour is the only mod enabled

**Comment by prodzpod** [comment]
fixed in this version
